[package]
name = "stealer"
version = "0.1.0"
authors = ["Joshua Narayana <europajuice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "*"
crossbeam-utils = "*"
arrayvec = "*"